services:
  product:
    url: http://localhost:8082/api/store
  review:
    url: http://localhost:8086/api/review
  order:
    url: http://localhost:8084/api/order

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:10000
    producer:
      bootstrap-servers: localhost:10000

  elasticsearch:
    host: localhost


