spring:
  datasource:
    url: jdbc:postgresql://baedal:5432/baedal-store
    username: baedal
    password: baedal
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: baedal-kafka:9092
    producer:
      bootstrap-servers: baedal-kafka:9092


services:
  product:
    url: http://store:8082/api/store
  review:
    url: http://review:8086/api/review
  order:
    url: http://order:8084/api/order
