server:
  port: 8081

services:
  product:
    url: http://localhost:8082/store
  review:
    url: http://localhost:8086/review
spring:
  #
  #  datasource:
  #    url: jdbc:postgresql://localhost:5433/store
  #    username: store
  #    password: store
  #    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:10000
    producer:
      bootstrap-servers: localhost:10000